FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app

COPY gradle gradle
COPY gradlew build.gradle.kts settings.gradle.kts ./

RUN chmod +x gradlew && ./gradlew dependencies --no-daemon

COPY src ./src

EXPOSE 8080 5005

CMD ["./gradlew", "bootRun", "--args='--spring.profiles.active=dev --spring-boot.run.jvmArguments=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005'"]