services:
  db:
    image: postgres:15-alpine
    container_name: expenses-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: expenses_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - expenses-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: expenses-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - expenses-network

volumes:
  postgres_data: {}

networks:
  expenses-network:
    driver: bridge